using CodeGen.Result;
using CodeGen.Result.Models;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CodeGen.Result.Controllers;

/// <summary>
/// This code is automatically generated by CodeGen Api command
/// </summary>
public class CustomController : Controller
{
    private readonly SampleContext _context;

    public CustomController(SampleContext context)
    {
        _context = context;
    }

    // GET: MultiTable
    public async ValueTask<IActionResult> Index()
    {
        return View(await _context.MultiTables.ToListAsync());
    }

    [HttpGet]
    public async ValueTask<ActionResult<IEnumerable<MultiTable>>> Get([FromQuery] DataTableParameters parameters)
    {
        IQueryable<MultiTable> query;
        if (!string.IsNullOrWhiteSpace(parameters.Search?.Value))
        {
            query = _context.MultiTables.WhereAllColumns(parameters.Search?.Value ?? "");
        }
        else
        {
            query = _context.MultiTables;
        }

        foreach (var i in parameters.SearchBuilder.SearchConditions)
        {
            query = query.WhereColumns(parameters.SearchBuilder);
        }

        IOrderedQueryable<MultiTable> ordered = query.OrderBy(x => x);
        if (parameters.Order.Count > 0)
        {
            var o = parameters.Order[0];
            if (o.Dir == ColumnOrderDir.asc)
            {
                ordered = query.OrderBy(parameters.Columns[o.Column + 2].Data);
            }
            else
            {
                ordered = query.OrderByDescending(parameters.Columns[o.Column + 2].Data);
            }

            foreach (var ox in parameters.Order.Skip(1).Select((x, index) => (x, index)))
            {
                var cx = parameters.Columns[ox.x.Column + 2];
                if (ox.x.Dir == ColumnOrderDir.asc)
                {
                    ordered = ordered.ThenBy(cx.Data);
                }
                else
                {
                    ordered = ordered.ThenByDescending(cx.Data);
                }
            }
        }

        var takes = ordered.Skip(parameters.Start).Take(parameters.Length);

        // 全件数を取得
        var totalCount = query.Count();

        // データと合計件数をレスポンスで返す
        return Json(new
        {
            data = await takes.ToListAsync(),
            recordsFiltered = totalCount,
            recordsTotal = totalCount
        });
    }

    private enum MultiTableColumn
    {
        Id, Charid, TargetName
    }

    // GET: MultiTable/Details/5
    public async ValueTask<IActionResult> Details(int id, string charid)
    {
        var target = _context.MultiTables.AsNoTracking();
        target = target.Where(x => x.Id == id);
        target = target.Where(x => x.Charid == charid);
        var result = await target.SingleOrDefaultAsync();

        if (result == null)
        {
            return NotFound();
        }

        return View(result);
    }

    // GET: MultiTable/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: MultiTable/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async ValueTask<IActionResult> Create([Bind("Id,Charid,TargetName,TargetInt,TargetDecimal,TargetDate,TargetBit,CreateAt,CreateUser,UpdateAt,UpdateUser")] MultiTable target)
    {
        if (ModelState.IsValid)
        {
            _context.Add(target);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(target);
    }

    // GET: MultiTable/Edit/5
    public async ValueTask<IActionResult> Edit(int id, string charid)
    {
        var target = _context.MultiTables.AsNoTracking();
        target = target.Where(x => x.Id == id);
        target = target.Where(x => x.Charid == charid);
        var result = await target.SingleOrDefaultAsync();

        if (result == null)
        {
            return NotFound();
        }
        return View(result);
    }

    // POST: MultiTable/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async ValueTask<IActionResult> Edit(int id, string charid, [Bind("Id,Charid,TargetName,TargetInt,TargetDecimal,TargetDate,TargetBit,CreateAt,CreateUser,UpdateAt,UpdateUser")] MultiTable target)
    {
        if (target.Id != id || target.Charid != charid)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(target);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!Exists(id, charid))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(target);
    }

    // GET: MultiTable/Delete/5
    public async ValueTask<IActionResult> Delete(int id, string charid)
    {
        var target = _context.MultiTables.AsNoTracking();
        target = target.Where(x => x.Id == id);
        target = target.Where(x => x.Charid == charid);
        var result = await target.SingleOrDefaultAsync();

        if (result == null)
        {
            return NotFound();
        }

        return View(result);
    }

    // POST: MultiTable/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async ValueTask<IActionResult> DeleteConfirmed(int id, string charid)
    {
        var target = _context.MultiTables.AsNoTracking();
        target = target.Where(x => x.Id == id);
        target = target.Where(x => x.Charid == charid);
        var result = await target.SingleOrDefaultAsync();

        if (result != null)
        {
            _context.MultiTables.Remove(result);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool Exists(int id, string charid)
    {
        var target = _context.MultiTables.AsNoTracking();
        target = target.Where(x => x.Id == id);
        target = target.Where(x => x.Charid == charid);
        return target.Any();
    }
}
