<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>

    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.10" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="TUnit" Version="1.5.80" />
    <PackageReference Include="TUnit.Playwright" Version="1.5.80" />
    <PackageReference Include="Testcontainers" Version="4.3.0" />
    <PackageReference Include="Testcontainers.Keycloak" Version="4.3.0" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="TUnit.Core" />
    <Using Include="TUnit.Assertions" />
    <Using Include="TUnit.Playwright" />
    <Using Include="Microsoft.Playwright" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../testcontainer/migrate/*" LinkBase="migrate"
      CopyToOutputDirectory="PreserveNewest" />
    <None Include="../testcontainer/Test-realm.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AspNetCoreSample.Mvc\AspNetCoreSample.Mvc.csproj" />
  </ItemGroup>

</Project>
