using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace __NamespaceName__;

/// <summary>
/// This code is automatically generated by CodeGen Api command
/// </summary>
__Authorize__
[Route("api/[controller]")]
[ApiController]
public class __ControllerName__ : ControllerBase
{
    private readonly __ContextTypeName__ _context;

    public __ControllerName__(__ContextTypeName__ context)
    {
        _context = context;
    }

    // GET: @routePrefix
    [HttpGet]
    public async ValueTask<ActionResult<IEnumerable<__ModelTypeName__>>> Get()
    {
        return await _context.__EntitySetName__.ToListAsync();
    }

    // GET: @routePrefix/5
    [HttpGet("{id}")]
    public async ValueTask<ActionResult<__ModelTypeName__>> Get(__PrimaryKeyShortTypeName__ id)
    {
        var target = await _context.__EntitySetName__.FindAsync(id);

        if (target == null)
        {
            return NotFound();
        }

        return target;
    }

    // PUT: @routePrefix/5
    // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
    [HttpPut("{id}")]
    public async ValueTask<IActionResult> Put(__PrimaryKeyShortTypeName__ id, __ModelTypeName__ target)
    {
        if (id != target.__PrimaryKeyName__)
        {
            return BadRequest();
        }

        _context.Entry(target).State = EntityState.Modified;

        try
        {
            await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
            if (!Exists(id))
            {
                return NotFound();
            }
            else
            {
                throw;
            }
        }

        return NoContent();
    }

    // POST: @routePrefix
    // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
    [HttpPost]
    public async ValueTask<ActionResult<__ModelTypeName__>> Post(__ModelTypeName__ target)
    {
        _context.__EntitySetName__.Add(target);

        try
        {
            await _context.SaveChangesAsync();
        }
        catch (DbUpdateException)
        {
            if (Exists(target.__PrimaryKeyName__))
            {
                return Conflict();
            }
            else
            {
                throw;
            }
        }

        return CreatedAtAction("Get", new { id = target.__PrimaryKeyName__ }, target);
    }

    // DELETE: @routePrefix/5
    [HttpDelete("{id}")]
    public async ValueTask<IActionResult> Delete(__PrimaryKeyShortTypeName__ id)
    {
        var target = await _context.__EntitySetName__.FindAsync(id);
        if (target == null)
        {
            return NotFound();
        }

        _context.__EntitySetName__.Remove(target);
        await _context.SaveChangesAsync();

        return NoContent();
    }

    private bool Exists(__PrimaryKeyShortTypeName__ id)
    {
        return _context.__EntitySetName__.Any(e => e.__PrimaryKeyName__ == id);
    }
}
