namespace @NamespaceName@;

/// <summary>
/// This code is automatically generated by CodeGen Sample command
/// </summary>
public class @ClassName@
{
    public void @MethodName@()
    {
    }

@MethodLevel@
}
