<Project>
    <PropertyGroup Condition="$(IsTestProject) == 'true'">
        <CollectCoverage>true</CollectCoverage>
        <CoverletOutputFormat>cobertura</CoverletOutputFormat>
        <CoverletOutput>$(MSBuildProjectDirectory)/TestResults/coverage.cobertura.xml</CoverletOutput>
        <ExcludeByAttribute>GeneratedCodeAttribute</ExcludeByAttribute>
    </PropertyGroup>
</Project>
