namespace __NamespaceName__;

/// <summary>
/// This code is automatically generated by CodeGen Sample command
/// </summary>
public class __ClassName__
{
    public void __MethodName__()
    {
    }

    __MethodLevel__
}
