<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="Npgsql" Version="9.0.3" />
    <PackageReference Include="Testcontainers" Version="4.3.0" />
    <PackageReference Include="Testcontainers.Keycloak" Version="4.3.0" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.3.0" />
    <PackageReference Include="TUnit" Version="1.5.53" />
    <PackageReference Include="TUnit.Assertions" Version="1.5.53" />
    <PackageReference Include="TUnit.Engine" Version="1.5.53" />
    <PackageReference Include="Verify.TUnit" Version="31.8.0" />
  </ItemGroup>



  <ItemGroup>
    <Using Include="TUnit.Core" />
    <Using Include="TUnit.Assertions" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../testcontainer/migrate/*" LinkBase="migrate"
      CopyToOutputDirectory="PreserveNewest" />
    <None Include="../testcontainer/Test-realm.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AspNetCoreSample.WebApi\AspNetCoreSample.WebApi.csproj" />
  </ItemGroup>

</Project>
